### ISSUE TITLE
Do not work on windows with vagrant 2.3.7

### ISSUE THREAD

**Issue by magnetik** [dustymabe/vagrant-sshfs#138]
I'm not sure if this is something known. 

But when trying the most simple example, I have :

```
/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/kernel_v2/config/vm.rb:300:in `synced_folder': can't add a new key into hash during iteration (RuntimeError)
from C:/Users/user/.vagrant.d/gems/3.1.3/gems/vagrant-sshfs-1.3.7/lib/vagrant-sshfs/action_hostpath_fixup.rb:74:in `block (2 levels) in loop_and_fix_unfix'

```

It seems to be coming from : https://github.com/dustymabe/vagrant-sshfs/blob/b6c4d7d74a56e83d88ce1e0cf5f5e1eb1704023b/lib/vagrant-sshfs/action_hostpath_fixup.rb#L74

Not sure if I'm doing something wrong.

Thanks.

**Comment by magnetik** [comment]
After a little search, it seems that it's something new from ruby 1.9 : https://stackoverflow.com/questions/25198085/is-there-a-solution-to-bypass-cant-add-a-new-key-into-hash-during-iteration-r

But since I know almost nothing in ruby I won't be able to fix it ! 

[edit] I'm such a ruby noob that I didn't knew that ruby 1.9 is super old
