### ISSUE TITLE
traceback when using wrong path

### ISSUE THREAD

**Issue by optak** [dustymabe/vagrant-sshfs#17]
if I use directory on host which doesn't exists, checking Mount section crash with traceback:
vagrant-sshfs (1.1.0)
Tested on windoes 10 in cygwin.

```
==> default: Mounting folder via SSHFS: /not/a/directory => /mnt/nothing
==> default: Checking Mount..
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
:/not/a/directory: No such file or directory
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:147:in `kill': Invalid argument (Errno::EINVAL)
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:147:in `sshfs_slave_mount'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:68:in `sshfs_mount_folder'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/capability_host.rb:111:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/capability_host.rb:111:in `capability'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/guest.rb:43:in `capability'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:78:in `block in enable'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:51:in `each'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:51:in `enable'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/command.rb:40:in `block in execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from C:/Users/cdk/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/command.rb:26:in `execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

**Comment by dustymabe** [comment]
@optak, thanks for the report.

**Comment by dustymabe** [comment]
hey @optak - can you try testing out vagrant-sshfs-1.1.0.dev.gem to see if you still have this issue? I tried but I think everything is working as expected (see output at bottom).

here is how to test:
```
vagrant plugin uninstall vagrant-sshfs
wget https://dustymabe.fedorapeople.org/gem/vagrant-sshfs-1.1.0.dev.gem
vagrant plugin install ./vagrant-sshfs-1.1.0.dev.gem
```

here is what I see now:

```
dustymabe@wintop /cygdrive/c/Users/dustymabe/Desktop/vagrantdirs/cdk
$ vagrant.exe sshfs
==> default: Mounting SSHFS shared folder...
==> default: Mounting folder via SSHFS: /not/a/dir => /foobar
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
:/not/a/dir: No such file or directory


SFTP command:



dustymabe@wintop /cygdrive/c/Users/dustymabe/Desktop/vagrantdirs/cdk
$ vagrant.exe destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
v==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...

dustymabe@wintop /cygdrive/c/Users/dustymabe/Desktop/vagrantdirs/cdk
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: /not/a/dir
```

**Comment by dustymabe** [comment]
@optak can you try against the latest version (1.2.0)?

**Comment by dustymabe** [comment]
@optak ^^

**Comment by dustymabe** [comment]
I think this is no longer an issue. If you find it is please re-open.
