### ISSUE TITLE
traceback when mount fails on windows

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/vagrant-sshfs#21]
Working with vagrant-sshfs 1.1.0 and vagrant 1.7.4 on windows. How to reproduce:

Have vagrant box already up (otherwise you will get an error from other part of vagrant):
```
vagrant up
```

Now add following line to your Vagrantfile
```
config.vm.synced_folder "/does/not/exist", "/foobar/", type: "sshfs"
```

Then `vagrant sshfs`:

```
$ vagrant.exe sshfs
==> default: Mounting SSHFS shared folders...
==> default: Mounting folder via SSHFS: /does/not/exist => /foobar
==> default: Checking Mount..
Warning: Permanently added '[127.0.0.1]:2200' (ECDSA) to the list of known hosts.
:/does/not/exist: No such file or directory
==> default: Checking Mount..
==> default: Checking Mount..
==> default: Checking Mount..
C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:148:in `kill': No such process (Errno::ESRCH)
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:148:in `sshfs_slave_mount'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/cap/linux/sshfs_mount.rb:68:in `sshfs_mount_folder'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/capability_host.rb:111:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/capability_host.rb:111:in `capability'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/guest.rb:43:in `capability'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:89:in `block in enable'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:51:in `each'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/synced_folder.rb:51:in `enable'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/command.rb:40:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/Users/dustymabe/.vagrant.d/gems/gems/vagrant-sshfs-1.1.0/lib/vagrant-sshfs/command.rb:26:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'

```

**Comment by dustymabe** [comment]
This is because windows does not respect Process.kill("TERM", pid). It only recognizes "KILL". See https://blog.simplificator.com/2016/01/18/how-to-kill-processes-on-windows-using-ruby/
