### ISSUE TITLE
Mount under root owned folder fails in 1.3.0

### ISSUE THREAD

**Issue by jlebon** [dustymabe/vagrant-sshfs#65]
After upgrading to 1.3.0, I get stuck at "Checking Mount.." when starting a halted machine. Full output:

```
$ rpm -q vagrant ruby vagrant-sshfs
vagrant-1.8.1-5.fc24.noarch
ruby-2.3.1-56.fc24.x86_64
vagrant-sshfs-1.3.0-1.fc24.noarch
$ vagrant up
Bringing machine 'vmcheck' up with 'libvirt' provider...
==> vmcheck: Starting domain.
==> vmcheck: Waiting for domain to get an IP address...
==> vmcheck: Waiting for SSH to become available...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> vmcheck: Creating shared folders metadata...
==> vmcheck: Mounting SSHFS shared folder...
==> vmcheck: Mounting folder via SSHFS: /code/github.com/projectatomic/rpm-ostree/vagrant-dev => /var/roothome/sync
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
==> vmcheck: Checking Mount..
Mounting SSHFS shared folder via slave SSHFS mount failed. Please
look at the below STDERR output from the processes that were run.

SSH command:

Warning: Permanently added '192.168.121.201' (ECDSA) to the list of known hosts.


SFTP command:
```

This is the Vagrantfile that I'm using: https://github.com/projectatomic/rpm-ostree/blob/master/Vagrantfile (though note the `fuse-sshfs` workaround mentioned in: https://github.com/projectatomic/rpm-ostree/tree/master/vagrant).

Reverting back to 1.2.1 works.

**Comment by dustymabe** [comment]
This has to do with the fact that you are trying to mount in a directory owned by root. The checks that I added recently run some commands without sudo and those checks are failing now. 

I'll put in a PR soon to resolve this.
